-- Schema SQL para criação das tabelas do banco de dados
-- Arquivo de schema para desenvolvimento com banco H2
-- Este arquivo será executado antes do data.sql

-- Criação da tabela orixas
CREATE TABLE IF NOT EXISTS orixas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(50) UNIQUE NOT NULL,
    nome_africano      VARCHAR(50),
    descricao          TEXT NOT NULL,
    cor_primaria       VARCHAR(7),
    cor_secundaria     VARCHAR(7),
    dia_semana         VARCHAR(20),
    elemento           VARCHAR(30),
    sincretismo        VARCHAR(100),
    icone_representacao VARCHAR(50),
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ativo              BOOLEAN DEFAULT TRUE
);
