
-- Schema SQL para criação das tabelas do banco de dados
-- Arquivo de schema para desenvolvimento com banco H2
-- Este arquivo será executado antes do data.sql

-- Criação da tabela orixas
CREATE TABLE IF NOT EXISTS orixas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(50) UNIQUE NOT NULL,
    nome_africano      VARCHAR(50),
    descricao          TEXT NOT NULL,
    cor_primaria       VARCHAR(7),
    cor_secundaria     VARCHAR(7),
    dia_semana         VARCHAR(20),
    elemento           VARCHAR(30),
    sincretismo        VARCHAR(100),
    icone_representacao VARCHAR(50),
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ativo              BOOLEAN DEFAULT TRUE
);

-- Criação da tabela linhas
CREATE TABLE IF NOT EXISTS linhas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(80) UNIQUE NOT NULL,
    orixa_regente_id   BIGINT NOT NULL,
    orixa_adjunto_id   BIGINT,
    descricao          TEXT NOT NULL,
    caracteristicas    TEXT,
    cores              VARCHAR(100),
    elementos_trabalho VARCHAR(200),
    numero_ordem       INTEGER,
    ativo              BOOLEAN DEFAULT TRUE,
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (orixa_regente_id) REFERENCES orixas(id),
    FOREIGN KEY (orixa_adjunto_id) REFERENCES orixas(id)
);

-- Criação da tabela tipos_entidade
CREATE TABLE IF NOT EXISTS tipos_entidade (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(80) UNIQUE NOT NULL,
    linha_id           BIGINT,
    descricao          TEXT NOT NULL,
    caracteristicas    TEXT,
    area_atuacao       VARCHAR(200),
    icone_representacao VARCHAR(50),
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ativo              BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (linha_id) REFERENCES linhas (id)
);

-- Criação da tabela entidades_especificas
CREATE TABLE IF NOT EXISTS entidades_especificas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(100) UNIQUE NOT NULL,
    tipo_entidade_id   BIGINT NOT NULL,
    linha_id           BIGINT,
    descricao          TEXT,
    historia           TEXT,
    caracteristicas_especificas TEXT,
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ativo              BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (tipo_entidade_id) REFERENCES tipos_entidade(id),
    FOREIGN KEY (linha_id) REFERENCES linhas(id)
);

-- Criação da tabela finalidades
CREATE TABLE IF NOT EXISTS finalidades (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(80) UNIQUE NOT NULL,
    descricao          TEXT NOT NULL,
    categoria          VARCHAR(50),
    uso_ritual         TEXT,
    momento_gira       VARCHAR(100),
    ativo              BOOLEAN DEFAULT TRUE
);
