
DROP TABLE IF EXISTS youtube_urls;
DROP TABLE IF EXISTS ponto_cantado_tags;
DROP TABLE IF EXISTS pontos_cantados;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS finalidades;
DROP TABLE IF EXISTS entidades_especificas;
DROP TABLE IF EXISTS tipos_entidade;
DROP TABLE IF EXISTS linhas;
DROP TABLE IF EXISTS orixas;
DROP TABLE IF EXISTS usuarios;

-- Schema SQL para criação das tabelas do banco de dados
-- Arquivo de schema para desenvolvimento com banco H2
-- Este arquivo será executado antes do data.sql

CREATE TABLE usuarios (
    id                  BIGSERIAL PRIMARY KEY,
    nome               VARCHAR(100) NOT NULL,
    email              VARCHAR(150) UNIQUE NOT NULL,
    senha_hash         VARCHAR(255) NOT NULL,
    role               VARCHAR(20) DEFAULT 'USER',
    status             VARCHAR(20) DEFAULT 'ATIVO',
    terreiro           VARCHAR(150),
    biografia          TEXT,
    foto_perfil_url    VARCHAR(500),
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultimo_login       TIMESTAMP,
    email_verificado   BOOLEAN DEFAULT FALSE,
    
    CONSTRAINT ck_usuario_role CHECK (role IN ('USER', 'MODERATOR', 'ADMIN')),
    CONSTRAINT ck_usuario_status CHECK (status IN ('ATIVO', 'INATIVO', 'BANIDO'))
);

-- Criação da tabela orixas
CREATE TABLE IF NOT EXISTS orixas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(50) UNIQUE NOT NULL,
    nome_africano      VARCHAR(50),
    descricao          TEXT NOT NULL,
    cor_primaria       VARCHAR(7),
    cor_secundaria     VARCHAR(7),
    dia_semana         VARCHAR(20),
    elemento           VARCHAR(30),
    sincretismo        VARCHAR(100),
    icone_representacao VARCHAR(50),
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ativo              BOOLEAN DEFAULT TRUE
);

-- Criação da tabela linhas
CREATE TABLE IF NOT EXISTS linhas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(80) UNIQUE NOT NULL,
    orixa_regente_id   BIGINT NOT NULL,
    orixa_adjunto_id   BIGINT,
    descricao          TEXT NOT NULL,
    caracteristicas    TEXT,
    cores              VARCHAR(100),
    elementos_trabalho VARCHAR(200),
    numero_ordem       INTEGER,
    ativo              BOOLEAN DEFAULT TRUE,
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (orixa_regente_id) REFERENCES orixas(id),
    FOREIGN KEY (orixa_adjunto_id) REFERENCES orixas(id)
);

-- Criação da tabela tipos_entidade
CREATE TABLE IF NOT EXISTS tipos_entidade (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(80) UNIQUE NOT NULL,
    linha_id           BIGINT,
    descricao          TEXT NOT NULL,
    caracteristicas    TEXT,
    area_atuacao       VARCHAR(200),
    icone_representacao VARCHAR(50),
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ativo              BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (linha_id) REFERENCES linhas (id)
);

-- Criação da tabela entidades_especificas
CREATE TABLE IF NOT EXISTS entidades_especificas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(100) UNIQUE NOT NULL,
    tipo_entidade_id   BIGINT NOT NULL,
    linha_id           BIGINT,
    descricao          TEXT,
    historia           TEXT,
    caracteristicas_especificas TEXT,
    data_criacao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ativo              BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (tipo_entidade_id) REFERENCES tipos_entidade(id),
    FOREIGN KEY (linha_id) REFERENCES linhas(id)
);

-- Criação da tabela finalidades
CREATE TABLE IF NOT EXISTS finalidades (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(80) UNIQUE NOT NULL,
    descricao          TEXT NOT NULL,
    categoria          VARCHAR(50),
    uso_ritual         TEXT,
    momento_gira       VARCHAR(100),
    ativo              BOOLEAN DEFAULT TRUE
);


-- Criação da tabela tags
CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) UNIQUE NOT NULL
);

-- Criação da tabela pontos_cantados
CREATE TABLE IF NOT EXISTS pontos_cantados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    letra_completa TEXT NOT NULL,
    linha_id BIGINT,
    orixa_id BIGINT,
    tipo_entidade_id BIGINT,
    entidade_especifica_id BIGINT,
    finalidade_id BIGINT,
    origem VARCHAR(20) DEFAULT 'TERRENO',
    ritmo VARCHAR(50),
    tonalidade VARCHAR(10),
    duracao_estimada INTEGER,
    observacoes TEXT,
    autor_letra VARCHAR(150),
    terreiro_origem VARCHAR(150),
    regiao_origem VARCHAR(100),
    data_contribuicao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_contribuidor_id BIGINT NOT NULL,
    status_moderacao VARCHAR(20) DEFAULT 'PENDENTE',
    moderador_id BIGINT,
    data_moderacao TIMESTAMP,
    motivo_rejeicao TEXT,
    visualizacoes INTEGER DEFAULT 0,
    ativo BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (linha_id) REFERENCES linhas(id),
    FOREIGN KEY (orixa_id) REFERENCES orixas(id),
    FOREIGN KEY (tipo_entidade_id) REFERENCES tipos_entidade(id),
    FOREIGN KEY (entidade_especifica_id) REFERENCES entidades_especificas(id),
    FOREIGN KEY (finalidade_id) REFERENCES finalidades(id),
    FOREIGN KEY (usuario_contribuidor_id) REFERENCES usuarios(id),
    FOREIGN KEY (moderador_id) REFERENCES usuarios(id),
    CONSTRAINT ck_ponto_origem CHECK (origem IN ('RAIZ', 'TERRENO')),
    CONSTRAINT ck_ponto_status CHECK (status_moderacao IN ('PENDENTE', 'APROVADO', 'REJEITADO'))
);

-- Criação da tabela de associação ponto_cantado_tags (N:N)
CREATE TABLE IF NOT EXISTS ponto_cantado_tags (
    ponto_cantado_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (ponto_cantado_id, tag_id),
    FOREIGN KEY (ponto_cantado_id) REFERENCES pontos_cantados(id),
    FOREIGN KEY (tag_id) REFERENCES tags(id)
);

-- Criação da tabela youtube_urls
CREATE TABLE IF NOT EXISTS youtube_urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ponto_cantado_id BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    status_moderacao VARCHAR(20) DEFAULT 'PENDENTE',
    moderador_id BIGINT,
    data_moderacao TIMESTAMP,
    motivo_rejeicao TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (ponto_cantado_id) REFERENCES pontos_cantados(id),
    FOREIGN KEY (moderador_id) REFERENCES usuarios(id),
    CONSTRAINT ck_youtube_status CHECK (status_moderacao IN ('PENDENTE', 'APROVADO', 'REJEITADO'))
);
